apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brierley-prod
  region: eu-west-2

nodeGroups:
  - name: full-stack-nodes
    instanceType: t3.large
    desiredCapacity: 5
    minSize: 4
    maxSize: 6
    volumeSize: 20
    ssh:
      allow: true

