apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brierley-prod-k8s
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    ssh:
      allow: true

